### ISSUE TITLE
[Question] Disable Screensaver

### ISSUE THREAD

**Issue by newhinton** [olicooper/esphome-nspanel-lovelace-native#40]
Hi!

Is it possible to disable the screensaver, so that it always shows the first page instead of time/weather?
Commenting out the screensaver-section only breaks it's layout :D

Thanks!

**Comment by olicooper** [comment]
Could you try setting `sleep_timeout: 0` like is seen in the [advanced-example.yaml](https://github.com/olicooper/esphome-nspanel-lovelace-native/blob/edc4b935407bcdd21418d1a157439185a0561faf/advanced-example.yaml#L30-L32) and let me know if that works? It should then go straight to the first card in your config.
https://github.com/olicooper/esphome-nspanel-lovelace-native/blob/edc4b935407bcdd21418d1a157439185a0561faf/advanced-example.yaml#L30-L32

**Comment by newhinton** [comment]
Thanks for the quick answer! 

Though sadly that does not seem to work:

```
nspanel_lovelace:
  id: nspanel
  sleep_timeout: 0 
  screensaver:
    time_id: homeassistant_time
    weather:
      entity_id: !secret weather_entity_id
```

Using Home Assistant to turn on the backlight (or pressing a button) wakes the device, but the screensaver is still the first screen. Only after tapping the screen i get my first card.

But you are right, as per the original appdaemon-variant, `sleepTimeout 0` should disable the screensaver:
https://docs.nspanel.pky.eu/stable/config-overview/

**Comment by newhinton** [comment]
Hi! Thanks for the fix! 

It does seem to be required to set the timeout on every card, and after a device reboot you have to "unlock" it once, but that is totally fine. 

Fiy, it seems c35fb9508be321d48edb378bc17e2059b28030a0 doesn't allow me to build with esphome 2025.6.x.

So if anyone has the following error too, you need to update esphome to 2025.7 which then seems to work.

```
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:32:49: error: expected class-name before '{' token
   32 | struct SpiRamAllocator : ArduinoJson::Allocator {
      |                                                 ^
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:33:9: error: 'void* esphome::nspanel_lovelace::SpiRamAllocator::allocate(size_t)' marked 'override', but does not override
   33 |   void* allocate(size_t size) override {
      |         ^~~~~~~~
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:40:8: error: 'void esphome::nspanel_lovelace::SpiRamAllocator::deallocate(void*)' marked 'override', but does not override
   40 |   void deallocate(void* pointer) override {
      |        ^~~~~~~~~~
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:47:9: error: 'void* esphome::nspanel_lovelace::SpiRamAllocator::reallocate(void*, size_t)' marked 'override', but does not override
   47 |   void* reallocate(void* ptr, size_t new_size) override {
      |         ^~~~~~~~~~
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp: In member function 'void esphome::nspanel_lovelace::NSPanelLovelace::on_weather_forecast_update_(std::string, std::string)':
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2313:29: error: 'ArduinoJson6185_71::JsonDocument::JsonDocument()' is protected within this context
 2313 |   ArduinoJson::JsonDocument filter;
      |                             ^~~~~~
In file included from .piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from .piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson.hpp:21,
                 from .piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson.h:9,
                 from src/esphome/components/json/json_util.h:11,
                 from src/esphome/core/string_ref.h:11,
                 from src/esphome/core/entity_base.h:5,
                 from src/esphome/components/binary_sensor/binary_sensor.h:4,
                 from src/esphome/core/controller.h:5,
                 from src/esphome/components/api/api_server.h:11,
                 from src/esphome/components/api/custom_api_device.h:4,
                 from src/esphome/components/nspanel_lovelace/nspanel_lovelace.h:18,
                 from src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:1:
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:306:3: note: declared protected here
  306 |   JsonDocument() : _pool(0, 0) {
      |   ^~~~~~~~~~~~
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2313:29: error: 'ArduinoJson6185_71::JsonDocument::~JsonDocument()' is protected within this context
 2313 |   ArduinoJson::JsonDocument filter;
      |                             ^~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:318:3: note: declared protected here
  318 |   ~JsonDocument() {}
      |   ^
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2327:30: error: no matching function for call to 'ArduinoJson6185_71::JsonDocument::JsonDocument(esphome::nspanel_lovelace::SpiRamAllocator*)'
 2327 |   JsonDocument doc(&allocator);
      |                              ^
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:336:3: note: candidate: 'ArduinoJson6185_71::JsonDocument::JsonDocument(const ArduinoJson6185_71::JsonDocument&)'
  336 |   JsonDocument(const JsonDocument&);
      |   ^~~~~~~~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:336:16: note:   no known conversion for argument 1 from 'esphome::nspanel_lovelace::SpiRamAllocator*' to 'const ArduinoJson6185_71::JsonDocument&'
  336 |   JsonDocument(const JsonDocument&);
      |                ^~~~~~~~~~~~~~~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:314:3: note: candidate: 'ArduinoJson6185_71::JsonDocument::JsonDocument(char*, size_t)'
  314 |   JsonDocument(char* buf, size_t capa) : _pool(buf, capa) {
      |   ^~~~~~~~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:314:3: note:   candidate expects 2 arguments, 1 provided
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:310:3: note: candidate: 'ArduinoJson6185_71::JsonDocument::JsonDocument(ArduinoJson6185_71::MemoryPool)'
  310 |   JsonDocument(MemoryPool pool) : _pool(pool) {
      |   ^~~~~~~~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:310:27: note:   no known conversion for argument 1 from 'esphome::nspanel_lovelace::SpiRamAllocator*' to 'ArduinoJson6185_71::MemoryPool'
  310 |   JsonDocument(MemoryPool pool) : _pool(pool) {
      |                ~~~~~~~~~~~^~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:306:3: note: candidate: 'ArduinoJson6185_71::JsonDocument::JsonDocument()'
  306 |   JsonDocument() : _pool(0, 0) {
      |   ^~~~~~~~~~~~
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:306:3: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp:2327:30: error: 'ArduinoJson6185_71::JsonDocument::~JsonDocument()' is protected within this context
 2327 |   JsonDocument doc(&allocator);
      |                              ^
.piolibdeps/rack-touch-panel/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:318:3: note: declared protected here
  318 |   ~JsonDocument() {}
      |   ^
*** [.pioenvs/rack-touch-panel/src/esphome/components/nspanel_lovelace/nspanel_lovelace.cpp.o] Error 1
```

**Comment by olicooper** [comment]
Thanks for the feedback! Yeah these issues need fixing.
I've just added a minimum version check so people aren't presented with that horrible error. I've checked back to esphome version `2025.5.0` and I will increment that as time goes on.

**Comment by olicooper** [comment]
Could you update your nspanel and check that the issues you faced before have now been fixed? You don't need to test the esphome version compile issue.

**Comment by newhinton** [comment]
What exactly do you mean? After updating i haven't had the issue with esphome itself, but the "unlock-after-reboot" and "sleep_timeout-on-every-card" are the same.
